language: cpp

compiler:
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq build-essential cmake git-core libboost-dev libboost-filesystem-dev libboost-system-dev libboost-program-options-dev libtbb-dev libqt4-dev libunittest++-dev libvtk5-dev libvtk5-qt4-dev libopencv-dev libusb-1.0-0-dev libcv-dev libhighgui-dev libdc1394-22 libdc1394-22-dev
  - wget http://www.phidgets.com/downloads/libraries/libphidget.tar.gz
  - tar xzvf libphidget.tar.gz && cd libphidget*
  - ./configure && make && sudo make install
  - cd ..
  - git clone https://github.com/rmsalinas/aruco.git
  - cd aruco/trunk/
  - mkdir build && cd build
  - cmake ..
  - make && sudo make install
  - cd ../../../

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make

branches:
  only:
    - develop
